In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('data/raw/faostat/turkey_hazelnut_production.csv')

In [8]:
df.tail(20)

    year  production_mt
44  2005       530000.0
45  2006       661000.0
46  2007       530000.0
47  2008       800791.0
48  2009       500000.0
49  2010       600000.0
50  2011       430000.0
51  2012       660000.0
52  2013       549000.0
53  2014       450000.0
54  2015       646000.0
55  2016       420000.0
56  2017       675000.0
57  2018       515000.0
58  2019       776046.0
59  2020       665000.0
60  2021       684000.0
61  2022       765000.0
62  2023       650000.0
63  2024       717000.0

In [12]:
frost = pd.read_csv('data/raw/era5_frost_monthly.csv')

In [13]:
frost

    year   march_dh   april_dh    frost_dh
0   1990   0.817577   0.517844    1.335420
1   1991   0.078690   0.000000    0.078690
2   1992   7.123327   0.009482    7.132809
3   1993   1.014252   1.387186    2.401437
4   1994   0.000000   0.058133    0.058133
5   1995   4.789377   5.338163   10.127541
6   1996   0.000000   0.200153    0.200153
7   1997  64.176872  37.235672  101.412544
8   1998  22.053326   0.000000   22.053326
9   1999   3.186011   0.000000    3.186011
10  2000  24.797356   3.523218   28.320574
11  2001   0.000000   0.000000    0.000000
12  2002   0.003510   0.360858    0.364368
13  2003  36.906769   7.198995   44.105762
14  2004   0.000000  13.347246   13.347246
15  2005   0.731055   2.304846    3.035902
16  2006   0.000000   0.028543    0.028543
17  2007   0.199612   0.695999    0.895612
18  2008   0.514059   0.000000    0.514059
19  2009   5.477530   0.016635    5.494164
20  2010   1.797433   0.000000    1.797433
21  2011   0.000000   0.000000    0.000000
22  2012  11.956892   0.041443   11.998335
23  2013   0.598804   0.000000    0.598804
24  2014   0.474374   0.000000    0.474374
25  2015   0.290729   8.462154    8.752883
26  2016   1.577038   0.000000    1.577038
27  2017   0.055325   1.081891    1.137216
28  2018   0.000000   0.002475    0.002475
29  2019   0.302438   0.128806    0.431244
30  2020   2.381454   0.000000    2.381454
31  2021   0.649445   1.114951    1.764395
32  2022  47.696823   0.215140   47.911964
33  2023   2.775626   0.000000    2.775626
34  2024   0.038803   0.000000    0.038803

In [ ]:
water = pd.read_csv('data/raw/spei/spei03_era5.csv')

In [ ]:
giresun = pd.read_csv("data/raw/giresun_spot_prices_monthly.csv")
giresun

,crop_year,year,month,period,total_qty_kg,total_value_tl,total_price_tl_kg,open_qty_kg,open_price_tl,fisko_qty_kg,fisko_price_tl,tmo_qty_kg,tmo_price_tl,fx_try_per_usd,avg_try_kg_inshell,avg_usd_kg_inshell,avg_try_kg_shelled,avg_usd_kg_shelled
0,2000,2001,1,full,3603153.0,4.314125e+06,1.197320,3600459.0,1.197433,2694.0,1.046208,0.0,0.00,677713.33,1.197320,1.70,2.660710,3.777778
1,2000,2001,2,full,3572307.0,4.431059e+06,1.240391,3566770.0,1.240612,5537.0,1.098138,0.0,0.00,670623.82,1.240391,1.70,2.756425,3.777778
2,2000,2001,3,full,4201042.0,6.142195e+06,1.462065,4201042.0,1.462065,0.0,0.000000,0.0,0.00,738109.45,1.462065,1.65,3.249033,3.666667
3,2000,2001,4,full,3770522.0,6.459724e+06,1.713217,3770522.0,1.713217,0.0,0.000000,0.0,0.00,965969.39,1.713217,1.37,3.807150,3.044444
4,2000,2001,5,full,1229198.0,2.367189e+06,1.925800,1229198.0,1.925800,0.0,0.000000,0.0,0.00,1206954.35,1.925800,1.27,4.279555,2.822222
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302,2024,2025,8,open,4212663.0,5.537888e+08,131.458133,4011954.0,131.320000,132717.0,132.890000,67992.0,136.54,NaN,131.458133,NaN,292.129183,NaN
303,2024,2024,9,full,19709443.0,2.557915e+09,129.781200,18353277.0,129.520000,654997.0,131.240000,701169.0,135.34,NaN,129.781200,NaN,288.402667,NaN
304,2024,2024,10,full,15686118.0,2.024830e+09,129.084222,14776060.0,129.020000,274826.0,126.260000,635232.0,131.91,NaN,129.084222,NaN,286.853827,NaN
305,2024,2024,11,full,13817894.0,1.818510e+09,131.605430,13312792.0,131.420000,455441.0,136.920000,49661.0,132.80,NaN,131.605430,NaN,292.456512,NaN
306,2024,2024,12,full,14781044.0,1.938562e+09,131.151882,14378918.0,131.010000,341523.0,136.650000,60603.0,133.90,NaN,131.151882,NaN,291.448627,NaN

:

In [23]:
tmo = pd.read_csv("data/raw/hazelnut_35yr_master.csv")

In [24]:
tmo

,Unnamed: 0,frost_dh,prod_mt,tmo_try,tmo_try_ret,tmo_active,prod_trend_5yr,prod_shortfall,is_on_year
0,1990,1.335420,375000.0,NaN,NaN,NaN,403333.333333,-0.070248,0
1,1991,0.078690,315000.0,NaN,NaN,NaN,378750.000000,-0.168317,0
2,1992,7.132808,520000.0,NaN,NaN,NaN,401000.000000,0.296758,1
3,1993,2.401437,305000.0,NaN,NaN,NaN,417000.000000,-0.268585,0
4,1994,0.058133,490000.0,NaN,NaN,NaN,443200.000000,0.105596,1
5,1995,10.127541,455000.0,NaN,NaN,NaN,421200.000000,0.080247,0
6,1996,0.200153,446000.0,NaN,NaN,NaN,476200.000000,-0.063419,0
7,1997,101.412576,410000.0,NaN,NaN,NaN,484200.000000,-0.153242,0
8,1998,22.053323,580000.0,NaN,NaN,NaN,487200.000000,0.190476,1
9,1999,3.186011,530000.0,NaN,NaN,NaN,523000.000000,0.013384,0
10,2000,28.320576,470000.0,NaN,NaN,0.0,561000.000000,-0.162210,0
11,2001,0.000000,625000.0,NaN,NaN,0.0,541000.000000,0.155268,1
12,2002,0.364368,600000.0,NaN,NaN,0.0,505000.000000,0.188119,0
13,2003,44.105782,480000.0,NaN,NaN,0.0,517000.000000,-0.071567,0
14,2004,13.347250,350000.0,NaN,NaN,0.0,524200.000000,-0.332316,0
15,2005,3.035901,530000.0,NaN,NaN,0.0,510200.000000,0.038808,1
16,2006,0.028543,661000.0,3.920963,NaN,1.0,574358.200000,0.150850,1
17,2007,0.895612,530000.0,5.382596,0.372774,1.0,604358.200000,-0.123037,0
18,2008,0.514059,800791.0,4.574795,-0.150077,1.0,618358.200000,0.295028,1
19,2009,5.494165,500000.0,NaN,NaN,0.0,572158.200000,-0.126116,0
20,2010,1.797433,600000.0,NaN,NaN,0.0,598158.200000,0.003079,1
21,2011,0.000000,430000.0,NaN,NaN,0.0,547800.000000,-0.215042,0
22,2012,11.998335,660000.0,NaN,NaN,0.0,537800.000000,0.227222,1
23,2013,0.598804,549000.0,NaN,NaN,0.0,547000.000000,0.003656,0
24,2014,0.474374,450000.0,NaN,NaN,0.0,545000.000000,-0.174312,0
25,2015,8.752883,646000.0,NaN,NaN,0.0,548000.000000,0.178832,1
26,2016,1.577038,420000.0,10.462911,NaN,1.0,541200.000000,-0.223947,0
27,2017,1.137216,675000.0,10.454473,-0.000806,1.0,606409.200000,0.113110,1
28,2018,0.002475,515000.0,14.511307,0.388048,1.0,610209.200000,-0.156027,0
29,2019,0.431244,776046.0,17.314106,0.193146,1.0,663009.200000,0.170491,1
30,2020,2.381454,665000.0,13.736622,-0.206623,1.0,681009.200000,-0.023508,0
31,2021,1.764395,684000.0,27.481867,1.000628,1.0,708009.200000,-0.033911,1
32,2022,47.911966,765000.0,54.788523,0.993624,1.0,696200.000000,0.098822,1
33,2023,2.775626,650000.0,88.680784,0.618601,1.0,704000.000000,-0.076705,0
34,2024,0.038803,717000.0,133.814465,0.508945,1.0,710666.666667,0.008912,1

In [22]:
basket = pd.read_csv("data/raw/basket/basket_dataset.csv")
basket

    year     tmo_eur  hazelnut_eur  almond_eur  walnut_eur
0   1985         NaN           NaN         NaN         NaN
1   1986         NaN           NaN         NaN         NaN
2   1987         NaN           NaN         NaN         NaN
3   1988         NaN           NaN         NaN         NaN
4   1989         NaN           NaN         NaN         NaN
5   1990         NaN           NaN         NaN         NaN
6   1991         NaN           NaN         NaN         NaN
7   1992         NaN           NaN         NaN         NaN
8   1993         NaN           NaN         NaN         NaN
9   1994         NaN           NaN         NaN         NaN
10  1995         NaN           NaN         NaN         NaN
11  1996         NaN           NaN         NaN         NaN
12  1997         NaN           NaN         NaN         NaN
13  1998         NaN           NaN         NaN         NaN
14  1999         NaN           NaN         NaN         NaN
15  2000         NaN           NaN         NaN         NaN
16  2001         NaN           NaN         NaN         NaN
17  2002         NaN           NaN         NaN         NaN
18  2003         NaN      3.940390    5.048624    3.940390
19  2004         NaN      4.728441    5.972768    4.728441
20  2005   58.386568      5.102386    6.844664    5.226835
21  2006   57.315274      4.524534    7.792254    6.032712
22  2007   73.296801      6.166311    9.729068    7.536602
23  2008   66.001755      7.058159    9.557924    7.646339
24  2009   77.641325      7.253678    8.090640    6.695702
25  2010   88.253875      9.019977    6.897630    5.969103
26  2011   85.070480      7.658449    6.683737    7.101471
27  2012  101.436593      7.971716    7.071684    7.457412
28  2013   91.058969      9.429592    8.234292    8.632725
29  2014  108.557825     11.297344    9.436605    9.569515
30  2015  107.880920     10.215557    9.438286    8.994132
31  2016  104.540966     11.624656   10.185413    9.963991
32  2017   96.078052     12.648499    9.938106    9.599307
33  2018   84.708730     10.395708    8.859978    8.505579
34  2019   90.059632     10.750419    9.182649    8.734715
35  2020   75.955719     13.473902   10.390891    9.705777
36  2021   56.103569     15.618486   10.057358   10.885611
37  2022   53.497046     15.804807    8.218500   10.641904
38  2023   42.168592           NaN         NaN         NaN
39  2024   47.179426           NaN         NaN         NaN